name: What's up docker

services:
  wud:
    image: getwud/wud:${WUD_VERSION}
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
      - wud_store:/store:rw
    environment:
      - WUD_TRIGGER_NTFY_PRIVATE_URL
      - WUD_TRIGGER_NTFY_PRIVATE_TOPIC=wud
      - WUD_TRIGGER_NTFY_PRIVATE_AUTH_TOKEN
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - backend
    restart: unless-stopped
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - traefik.enable=true
      - traefik.http.routers.wud-whatsupdocker.rule=Host(`${WUD_FQDN}`)
      - traefik.http.routers.wud-whatsupdocker.middlewares=ipallowlist@docker

networks:
  backend:
    external: true
    driver: bridge

volumes:
  wud_store:
